# configuration for https://github.com/EmbarkStudios/cargo-deny

[licenses]
default = "deny"
unlicensed = "deny"
copyleft = "deny"
confidence-threshold = 0.8
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
    "MPL-2.0",
    "ISC",
    "Unlicense",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
